version: '3'

services:

  daemon:
    container_name: coingraph-daemon
    build:
      context: daemon/.
      dockerfile: Dockerfile
    volumes:
      - './daemon/data:/usr/src/app/data'
    ports:
      - '8080:8080'
      - '8081:8081'
    env_file:
      - ./daemon/.env

  client:
    container_name: coingraph-client
    depends_on:
      - daemon
    links:
      - daemon
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
